### ISSUE TITLE
Support packages set up using Keijiro's workflow.

### ISSUE THREAD

**Issue by andybak** [omid3098/OpenPackageManagerRepository#2]
All his recent work has a UPM branch and he uses the built-in package manager to install them. It's a good half-way house until Unity supports 3rd party packages and it would mesh well with your approach. You'd have to relax the requirement to have a openpackage file in the repo root but it would open up the possibility for people to support your method as well as one along the same lines as Keijiro.

Good example here: https://github.com/keijiro/Flipper which uses: https://github.com/keijiro/Klak/tree/upm among others

**Comment by omid3098** [comment]
Thank you Andy. This method seems very good. However I did not understand the whole pipeline yet. will check this tomorrow.

**Comment by omid3098** [comment]
@andybak please correct me if I`m wrong.
Keijiro is defining his other packages as [sub modules](https://github.com/keijiro/Flipper/tree/master/Packages) in Packages directory and we have to sync submodules using git. so after initializing, everything there will be local. So what is the point of using UPM here?

The idea to have a separate branch for package management is good. we can even define BranchName property in .openpackage file and each developer can freely choose his/her own branch name and point to it in .openpackage file.

**Comment by andybak** [comment]
My thinking is as follows:

Both you and people following Keijiro's method (and possibly other workflows we don't know about) need people to change their repos for it to work.

Most people won't bother to modify their repo structure to support an obscure workflow.

However - if it's possible to support several different workflows (and potentially future official Unity support) with the same change - it will increase the likelihood of getting support.

Otherwise your only option will be to fork repos yourself, add openpackage and take responsibility for keeping the fork in sync.

**Comment by omid3098** [comment]
Yes, you are right, I need to understand the whole Keijiro's pipeline to decide its usage in OpenPackageManager workflow.

**Comment by andybak** [comment]
I actually started developing my own similar workflow: https://gist.github.com/andybak/f7573d2985aa6d1b905ed6519cb6a343

I tried messing around with git sparse checkouts so that I could fork a repo and checkout just a subset of it's folders but that proved to be more trouble than it was worth. The combination of git submodules and adding a package.json looked promising but I had to put it to one side before I was happy enough to try it in production.

I even got as far as forking lots of useful looking repos in preparation: https://github.com/UnityAssetPackages

**Comment by omid3098** [comment]
I think your method needs lots of maintenance for updating each package. however it does not need developer support. good luck and thanks for your suggestion. :+1:

**Comment by andybak** [comment]
> I think your method needs lots of maintenance for updating each package

I figured a single script to do git merge upstream might have worked. Anyway - it's on hold for now. I think I'll wait for official Unity support.
